name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Cloud Run
        working-directory: ./backend
        run: |
          gcloud run deploy bookscout-backend \
            --source . \
            --region europe-southwest1 \
            --allow-unauthenticated \
            --set-env-vars GOOGLE_BOOKS_API_KEY=${{ secrets.GCP_GOOGLE_BOOKS_API_KEY }}
